In [11]:
import numpy as np
a=np.array([5, 5, 5, 5, 5])
a



array([5, 5, 5, 5, 5])

In [10]:
type(a)


numpy.ndarray

In [13]:
b=np.zeros(5)
b


array([0., 0., 0., 0., 0.])

In [14]:
c=np.ones(3)
c


array([1., 1., 1.])

In [15]:
d=np.empty(3)
d


array([1., 1., 1.])

In [18]:
e=np.arange(4,20)
e

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
f=np.arange(6)
f

array([0, 1, 2, 3, 4, 5])

In [20]:
e=np.arange(4,20,3)
e

array([ 4,  7, 10, 13, 16, 19])

In [21]:
e=np.arange(0,100,2)
e

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [22]:
e=np.arange(0,100,3)
e


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
e=np.arange(1,100,2)
e


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [25]:
e=np.linspace(0,10,num=5)
e

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
e=np.linspace(0,50,num=10)
e

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])